/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEggRecord: typeof import('./src/components/AddEggRecord.vue')['default']
    AddInventory: typeof import('./src/components/AddInventory.vue')['default']
    AddNewBirdRecord: typeof import('./src/components/AddNewBirdRecord.vue')['default']
    AddNewCompany: typeof import('./src/components/AddNewCompany.vue')['default']
    AddNewEmployee: typeof import('./src/components/AddNewEmployee.vue')['default']
    AddNewExpense: typeof import('./src/components/AddNewExpense.vue')['default']
    AddNewRevenue: typeof import('./src/components/AddNewRevenue.vue')['default']
    AddNewUser: typeof import('./src/components/AddNewUser.vue')['default']
    AddSupplier: typeof import('./src/components/AddSupplier.vue')['default']
    BirdsAnalysisChart: typeof import('./src/components/charts/BirdsAnalysisChart.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Charts: typeof import('./src/components/Charts.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./src/components/AddNewUser copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EggsAnalysisChart: typeof import('./src/components/charts/EggsAnalysisChart.vue')['default']
    ExpenseView: typeof import('./src/components/ExpenseView.vue')['default']
    HeroSwiper: typeof import('./src/components/HeroSwiper.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    RevenueExpenditureChart: typeof import('./src/components/charts/RevenueExpenditureChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Tag: typeof import('primevue/tag')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UpdateBirdManagement: typeof import('./src/components/UpdateBirdManagement.vue')['default']
    UpdateCompany: typeof import('./src/components/UpdateCompany.vue')['default']
    UpdateEggRecord: typeof import('./src/components/UpdateEggRecord.vue')['default']
    UpdateEmployee: typeof import('./src/components/UpdateEmployee.vue')['default']
    UpdateExpense: typeof import('./src/components/UpdateExpense.vue')['default']
    UpdateInventory: typeof import('./src/components/UpdateInventory.vue')['default']
    UpdateRevenue: typeof import('./src/components/UpdateRevenue.vue')['default']
    UpdateSupplier: typeof import('./src/components/UpdateSupplier.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
  }
}
